name: Code Quality - Spotless

on:
  pull_request:
    branches:
      - main
      - 'release/**'
    types: [ opened, synchronize, reopened, ready_for_review ]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  spotless:
    name: Spotless Check
    runs-on: [ self-hosted, linux ]
    if: ${{ !github.event.pull_request.draft }}
    steps:
      - name: Checkout Code
        uses: actions/checkout@v5

      - name: Set Up JDK 21
        uses: actions/setup-java@v5
        with:
          distribution: temurin
          java-version: 21

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v4

      - name: Run Spotless Check
        run: |
          chmod +x ./gradlew
          ./gradlew spotlessCheck
